#!/bin/sh
echo "For those running USAGov locally:"
echo "This should download the static pages from a locally running docker container of the cms. Will excute: "
echo "      docker exec cms tar -c /var/www/html | tar -x -f - --strip-components=2 -C "
echo "If you need to generate the static files: docker exec -t cms sh /var/www/scripts/tome-static.sh http://localhost"
echo

rm -rf ../input/*.html
docker exec cms tar -c /var/www/html | tar -x -f - --strip-components=3 -C ../input
